spring:
  profiles:
    active: dev

server:
  port: 8210

---
spring:
  profiles: dev
  application:
    name: config-client
eureka:
  client:
    service-url:
      defaultZone: http://dev
---

server:
  port: 8202

spring:
  profiles: test
  application:
    name: config-client
eureka:
  client:
    service-url:
      defaultZone: http://test